project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2022" 
    right: 
      - icon: github
        href: https://github.com/
  title: "SAMIHA FAROOQI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - text: R Walkthrough
        menu:
        - href: map.qmd
          text: Sample Mapping
        - href: va_project.qmd
          text: Sample Project 1
        - href: r_walkthrough.qmd
          text: Sample Project 2
      - text: Articles
        menu: 
          - href: portfolio.qmd
            text: Published Archive 
          - href: example_article.qmd
            text: Example Breaking News Story
          - href: article1.qmd
            text: Sample Striketober Article
      - text: Writings
        menu:
        - href: walkthrough.qmd
          text: Sample Research Article
        - href: essay1.qmd
          text: Sample Essay
          
      


format:
  html:
    theme: lux
    css: styles.css
    toc: true



