project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2022, Testy R. Testman" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Samiha's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - portfolio.qmd
      - walkthrough.qmd
      


format:
  html:
    theme: lux
    css: styles.css
    toc: true



