project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2022, Testy R. Testman" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Samiha's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: map.qmd
        text: R Walkthrough
      - href: va_project.qmd
        text: R Project
      - href: portfolio.qmd
        text: Articles
      - href: walkthrough.qmd
        text: Writings
      


format:
  html:
    theme: lux
    css: styles.css
    toc: true



