---
title: "Sample Essay"
editor: visual
---

Below is a basic academic paper analyzing the role of the IMF in the global economy, written for a global economic history class.

# Privatize or Perish: The IMF's Guide to Devastating an International Economy

When an economic crisis emerges anywhere across the globe, it's only natural for the IMF, or International Monetary Fund, to step in. That is their intended purpose---to provide temporary financial assistance when needed, and promote economic growth and stability. However, by the time the East Asian regional financial crisis broke out in the 1990s, there was already doubt amongst East Asian leaders that the neoliberal policies the IMF are known to impose would be the cure needed to fix their economic ails. This is a problem, to say the least. Due to the policy conditions included in IMF bailout packages, trust in Western dominated, global financial institutions has been embarrassingly low---to the point that countries actively avoid turning to them in times of crisis. To add insult to injury, China and India---two of the only countries that have seen substantial economic growth in the last few decades---were able to avoid the same crisis as many of their neighbors in the 90s by doing exactly what the IMF warned not to do: imposing capital controls, and disregarding the Washington Consensus. This lack of faith in global financial institutions, coupled with the IMF's outright failure to adequately address economic crises, has contributed to an environment in which economic growth, worldwide, has stagnated. And unless the IMF finally chooses reality over ideology by focusing on restoring confidence in the system, economic growth will only continue to elude us all.

As Joseph Stiglitz recalls in his book, Globalization and its Discontents, leaders of the affected East Asian tigers "feared" that IMF policies would not allow them the room to properly manage their respective crises. However, they knew if they did not cooperate, the IMF would publicly "condemn" them, leading to a further withdrawal of international capital, and thus exacerbating the problem at hand. What Stiglitz points out is that these countries were, unfortunately, correct in their worries. Thailand, for example, followed the IMF's instructions to a T. They would soon wish they hadn't. Several years after the crisis began, Thailand had yet to see recovery---its economy was still in a recession, and its GDP was more than two percent lower than it had been prior to the crisis. At the same time, Malaysia and China were doing far better. Malaysia did not take part in any IMF program at all, despite the criticism this drew them. They handled the crisis on their own, and as a result, were able to recover much faster. Moreover, China did the exact opposite of everything the IMF said to do, allowing them to avoid the crisis completely. These kinds of results do not exactly inspire confidence in the IMF. But rather than admitting to any wrongdoing, they continue to push neoliberal monetary policies to this day.

The idea that the IMF is more concerned with bailing out investors rather than the people almost seems contradictory. One may be inclined to believe that no matter the amount of foreign aid bailouts, an economy can't truly recover without trust from the public. Be that as it may, the IMF cares little for its policies impact on people, considering the wealth will (probably) trickle down anyway. The resulting socio-political impact of their legacy, in East Asia and worldwide, is profound. Predictably, crushingly austere monetary policies that come along with their aid packages have a tendency to build resentment amongst the affected populations. With such disdain towards the IMF, countries are forced to try and accumulate as many dollars in their central bank as possible in an effort to prepare for a future economic crisis all on their own---subsequently delegitimizing the IMF as a genuinely internationalist institution, and actually leaving the market worse off due to this massive glut of dollars. With this in mind, it's vital to confront the question of who, exactly, the IMF helps---if not the people in the affected countries, or even the countries' economies and governments, for whom does a bailout actually serve to benefit?

Since the 1980s, economic growth has come to a slowdown around the world. Gone are the golden days of high growth, high wages, and high benefits that the Bretton Woods system delivered. Instead, nations around the globe---save for China and India---have been forced to reckon with stagflation, recession, and even outright depression. Post war institutions such as the IMF were once envisioned to be the solution to this sort of problem. However, over the last half century, it has been made abundantly clear who the IMF's bailout strategy seeks to protect more than anyone else: investors. Consequently, as Stiglitz points out, this has led the institution to forgetting about the people "in the countries it was supposed to be helping," and losing "sight of its original mission." This has had a dire effect on economic growth. By choosing to focus on investors over people, trust in the IMF is virtually nonexistent---and that has severe impacts on global economic and political relations. Growth cannot be expected to come if no one has faith in their political and economic institutions. By and large, the IMF is a Western dominated institution that serves mainly to impose their Washington Consensus---neoliberal policies---without regard for nuance or people. If they actually sought to build up trust in economies within countries that are in need of aid, perhaps they may be able to salvage some sort of political legitimacy outside the United States and its allies. Unfortunately, that is unlikely to happen, leaving many countries in need with one of two options: privatize or perish.
