---
title: "Articles Portfolio"
---

As a student journalist, I have conducted countless interviews in order to produce original reporting on the issues most affecting our communities---whether within the media itself, or during social phenomenon such as 'Striketober.' Below is a sample article about Striketober, which I was able to write by interviewing public servants in the DMV area. I have also linked my portfolios in MediaFile and the GW Hatchet.

### Article Sample: As 'Striketober' Turns to 'Strikemas,' Where Does That Leave Ordinary Workers? 

As her lunch break neared its end, Ismat Kumar rushed to head back to her office to clock back in. A healthcare worker at Kaiser Permanente in Northern Virginia, Kumar is more than used to the hustle and bustle that comes with working in medicine. In the 21 months since the COVID-19 pandemic began, however, it's becoming unbearable.

Since March 2020, Kumar said that Kaiser has made a number of controversial decisions for their staff. Lunch breaks have been shortened. Employees are now required to clock in and out for lunch. Overtime forms must be filled out every time a patient's appointment runs late. Fed up, Kumar says a number of her coworkers have quit or found new jobs---only adding to the stress of those who remain.

"Management will thank us, they'll call us heroes---all while benefits are being taken away," said Kumar. "They will listen to our complaints, but they won't do anything about them," she added.

What Kumar is experiencing right now is not uncommon. As the pandemic has raged on across the nation, and around the world, millions of workers have been faced with a stifling workplace. As Joseph McCartin, a professor of U.S. Labor, Social, and Political History at Georgetown University said, "as we're coming out of the pandemic, workers' expectations and desires regarding their jobs have changed a lot."

McCartin added that this phenomenon, called "the Great resignation," is largely a "worker driven labor shortage." Generally, workers are becoming more and more fed up with the conditions of their workplaces. Having constantly been called "heroes" without seeing an increase in their wages or benefits, many have either chosen to strike, or seek work elsewhere.

This is all occurring alongside what has been called "Striketober," and moving into December, "Strikesmas." According to The New York Times, more than 25,000 workers went on strike in October alone---compared to an average of about 10,000 workers in the previous three months.

"In a lot of these cases, people are complaining about the oppressive nature of their work," said McCartin. "And I think that really speaks to a broad shared experience that Americans have linked to the pandemic. This has led people to question whether they want to continue in the patterns that existed prior to the pandemic."

Maaz Ahmad, a public school teacher in Fairfax, VA, echoed similar experiences. The unions in Ahmad's county aren't very strong. This makes it difficult for the unions to actually make things happen. Something like a country-wide strike isn't feasible for them to organize. Being a right-to-work state such as Virginia complicates the situation, as unions are further weakened. Still, Ahmad said, "I assure you, if we announced that we were going to strike, most teachers in our county would do so, and we would completely shut down the county."

With the weakening of unions in recent decades, Rebecca Givan, a professor of Labor Studies and Employment Relations at Rutgers University, said,"it's clear that unions provide tangibly better work for workers. And so when there are fewer unions, workers do suffer."

Givan also said that the presence of strikes tends to raise people's awareness of them. Successful strikes make other workers realize that they could demand more, and receive significant wins. She added that, "in that way, strikes can be described as contagious."

Coming out of a difficult period of online schooling paired with the lack of wages, Ahmad also said that this school year has been "difficult." And as time goes on, he and other teachers are becoming more burnt out. "Whenever we go up the food chain and complain about salaries, that complaint is always set up above. That's why there is such a large exodus of teachers this year who are just fed up. And many of them are looking to find other jobs and other professions, because, one, they get paid more, and two, the professional respect that they get is higher."

Ahmad added that, "everyone needs to step up," from higher up officials in each county, to elected officials at both the state and federal levels.

What Ahmad is facing in his district is happening across the U.S., as teacher shortages are becoming increasingly dire. According to the Dept. of Labor Statistics, more than 270,000 public school teachers are projected to leave the profession between 2016 and 2026. A poll conducted by a well-known national teachers union showed that 1 and 3 teachers said it is likely they will retire or resign earlier than planned due to the pandemic.

One of the biggest complaints in Ahmad's district has been a freeze on raises. "Every year, your salary is supposed to go up," said Ahmad. "Except, in the last few years that hasn't happened. And if you include inflation, we've essentially been getting pay cuts."

Things are "spiraling out of control," said Ahmad. His county is directly feeling the impact of the teacher shortage. He said, "there are so many people who would be great teachers who are choosing not to join the profession because teachers aren't being compensated fairly. We have so many openings, and we just have put a warm body in there because no one wants the job."

While workers across several industries are quitting, according to the Dept. of Labor, 30,000 public school teachers left their jobs in September alone.

These shortages aren't confined to the classroom, as reported by PBS---from cafeteria workers to bus drivers, schools are experiencing shortages of all sorts of support staff. At least one school paid students to serve school lunches during the school day due to the staff.

As Ahmad said, students "aren't learning" because of the lack of qualified teachers there. He also said that there are a number of goods and services that are provided from schools for students, such as "a warm meal," and mental health services. "If schools can't provide those, because of a lack of funding or staff, then who will?"

## MediaFile Articles

While at MediaFileDC, a student run online paper, I I conducted original reporting by speaking to various academics and experts while covering stories on the international beat. At MediaFile, the goal for reporters is to find stories with some sort of media lens---for example, my [stories](https://www.mediafiledc.com/author/sfarooqi/) ranged from the Western media coverage of Afghan women, to the media scrutiny Meghan Markle faced from the UK press.

## GW Hatchet Articles

At The Hatchet, I covered two [stories](https://www.gwhatchet.com/author/samiha-farooqi/) on campus involving the implentation of GW's u-pass program, and the student and university responses to an assault, interviewing several students in the process.
