---
title: "A Sample Essay"
author: "Samiha Farooqi"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true
---

Below are two writing samples I have produced. The first is a basic paper analyzing the role of the IMF in the global economy, while the second is a formal research paper into how the pressure of grades may or may not affect a student's writing process.

# Privatize or Perish: The IMF's Guide to Devastating an International Economy

When an economic crisis emerges anywhere across the globe, it\'s only natural for the IMF, or International Monetary Fund, to step in. That is their intended purpose---to provide temporary financial assistance when needed, and promote economic growth and stability. However, by the time the East Asian regional financial crisis broke out in the 1990s, there was already doubt amongst East Asian leaders that the neoliberal policies the IMF are known to impose would be the cure needed to fix their economic ails. This is a problem, to say the least. Due to the policy conditions included in IMF bailout packages, trust in Western dominated, global financial institutions has been embarrassingly low---to the point that countries actively avoid turning to them in times of crisis. To add insult to injury, China and India---two of the only countries that have seen substantial economic growth in the last few decades---were able to avoid the same crisis as many of their neighbors in the 90s by doing exactly what the IMF warned not to do: imposing capital controls, and disregarding the Washington Consensus. This lack of faith in global financial institutions, coupled with the IMF\'s outright failure to adequately address economic crises, has contributed to an environment in which economic growth, worldwide, has stagnated. And unless the IMF finally chooses reality over ideology by focusing on restoring confidence in the system, economic growth will only continue to elude us all.

As Joseph Stiglitz recalls in his book, Globalization and its Discontents, leaders of the affected East Asian tigers \"feared\" that IMF policies would not allow them the room to properly manage their respective crises. However, they knew if they did not cooperate, the IMF would publicly \"condemn\" them, leading to a further withdrawal of international capital, and thus exacerbating the problem at hand. What Stiglitz points out is that these countries were, unfortunately, correct in their worries. Thailand, for example, followed the IMF\'s instructions to a T. They would soon wish they hadn\'t. Several years after the crisis began, Thailand had yet to see recovery---its economy was still in a recession, and its GDP was more than two percent lower than it had been prior to the crisis. At the same time, Malaysia and China were doing far better. Malaysia did not take part in any IMF program at all, despite the criticism this drew them. They handled the crisis on their own, and as a result, were able to recover much faster. Moreover, China did the exact opposite of everything the IMF said to do, allowing them to avoid the crisis completely. These kinds of results do not exactly inspire confidence in the IMF. But rather than admitting to any wrongdoing, they continue to push neoliberal monetary policies to this day.

The idea that the IMF is more concerned with bailing out investors rather than the people almost seems contradictory. One may be inclined to believe that no matter the amount of foreign aid bailouts, an economy can\'t truly recover without trust from the public. Be that as it may, the IMF cares little for its policies impact on people, considering the wealth will (probably) trickle down anyway. The resulting socio-political impact of their legacy, in East Asia and worldwide, is profound. Predictably, crushingly austere monetary policies that come along with their aid packages have a tendency to build resentment amongst the affected populations. With such disdain towards the IMF, countries are forced to try and accumulate as many dollars in their central bank as possible in an effort to prepare for a future economic crisis all on their own---subsequently delegitimizing the IMF as a genuinely internationalist institution, and actually leaving the market worse off due to this massive glut of dollars. With this in mind, it\'s vital to confront the question of who, exactly, the IMF helps---if not the people in the affected countries, or even the countries\' economies and governments, for whom does a bailout actually serve to benefit?

Since the 1980s, economic growth has come to a slowdown around the world. Gone are the golden days of high growth, high wages, and high benefits that the Bretton Woods system delivered. Instead, nations around the globe---save for China and India---have been forced to reckon with stagflation, recession, and even outright depression. Post war institutions such as the IMF were once envisioned to be the solution to this sort of problem. However, over the last half century, it has been made abundantly clear who the IMF\'s bailout strategy seeks to protect more than anyone else: investors. Consequently, as Stiglitz points out, this has led the institution to forgetting about the people \"in the countries it was supposed to be helping,\" and losing \"sight of its original mission.\" This has had a dire effect on economic growth. By choosing to focus on investors over people, trust in the IMF is virtually nonexistent---and that has severe impacts on global economic and political relations. Growth cannot be expected to come if no one has faith in their political and economic institutions. By and large, the IMF is a Western dominated institution that serves mainly to impose their Washington Consensus---neoliberal policies---without regard for nuance or people. If they actually sought to build up trust in economies within countries that are in need of aid, perhaps they may be able to salvage some sort of political legitimacy outside the United States and its allies. Unfortunately, that is unlikely to happen, leaving many countries in need with one of two options: privatize or perish.

# A Call to Abolish Grades

#### **Introduction:**

For years, there has been considerable pressure on k-12 public schools across the United States to perform well on state standardized tests. Often, performance on these tests dictate the amount of state or federal funding a district receives, and how high they rank comparatively.  In my home state of Massachusetts in particular, many schools specifically prepare for the writing portion of the state standardized test, MCAS, to ensure optimal results from students. Aside from preparation for standardized tests, schools frequently teach students certain \"rules'' of writing that they\'re required to follow; To do so otherwise could mean a failing grade. Given the rigidity of some of these rules of writing, as well as the general stress to perform well in school and on assessments, it\'s not difficult to imagine that students may see writing in a less than positive light---especially considering that many students are forced to alter their writing habits in order to conform to whatever rules their teacher requires. This, then, is why I began my research into the composing process in writing studies. In this paper, I will explore the origins of writer\'s block, as well as the extent of how standardized testing and/or rigid writing rules can add to it. 

I conducted my research by interviewing two college students: Kathy, a freshman at New York University (NYU), and Natalie, a freshman at the University of Vermont (UVM). Both of these students offer insight into their own personal relationships with writing, and the factors that influenced their respective relationships. For context, these students attended different types of high schools--Kathy attended private school from sixth through twelfth grades, while Natalie attended public school from kindergarten through twelfth grade. Furthermore, Kathy has a negative to average relationship with writing, while Natalie has a positive relationship with writing. In my research, I consider the occurrence of \"rules\" in each of their writing processes, as well as how their personal relationships with grades factor into their respective relationships with writing. I also analyze the school systems each student attended, and how the presence of state standardized exam preparation in school plays a role in how they approach writing. Through this, I hope to provide more clarity as to why some students may be more or less apt to write in college, the extent that k-12 education affects that, and, lastly, the way grades tend to negatively factor into it all. 

**Framework:**

Aside from the two interviews I conducted, I will be consulting the work of Mike Rose, as well as the work of Katherine Landau Wright. In Rose\'s article,  Rigid Rules, Inflexible Plans, and the Stifling of Language: A Cognitivist Analysis of Writer\'s Block, he demonstrates how the writing process is largely influenced by how a person approaches it. Rose states in his article that, \"\[the\] students who experienced blocking were all operating either with writing rules or with planning strategies that impeded rather than enhanced the composing process.\" In other words, the \"blockers,\" or the students who experienced writer\'s block, were actively contributing to their writer\'s block because of their preconceived beliefs in how the writing process must occur. It\'s clear, then, that the difficulties a writer may have in the \"composing process\" are not simply \"thinking\" problems; The real issue lies more in what a writer thinks to be true about writing. In other words, what \"rules\" they hold onto in the writing process. To relate this back to my research, students are often taught specific rules when approaching standardized writing assessments, and writing in general. Both Kathy and Natalie mention rules and/or strategies they were taught to use in their interviews, and while they both mention that those rules aided them in ways, it\'s clear they have set beliefs or routines in their respectives writing processes.

Katharine Landou Wright et al\'s work examines how middle schooler\'s motivation for writing changes from 6th through 8th grade. Though their research may not seem directly applicable---as it examines a different age group---the key ideas they discuss are still relevant to my research. Wright et all states that during \"testing years\" in school, the writing curriculum is altered in order to prepare students specifically for the test. In those years, student\'s motivation for writing tends to decrease. They specifically define \"attitude toward writing\" as something that \"generally predicts whether a student will respond in a favorable or unfavorable manner when encountering a writing task.\" Then, they discuss how students\' attitude toward writing was far less positive at the end of seventh grade--the year the specific school they study prepares for state exams. They state that, \"these \[negative\] experiences may have been related to some combination of the method of instruction or the stress related to preparing for and completing a high-stakes writing exam.\" In relation to my own research, Wright et al\'s work points to the idea that exam preparation in schools could negatively affect a student\'s attitude and/or general relationship with writing. For Kathy and Natalie specifically, I found that their respective relationships with writing is far more nuanced. However, it would still seem standardized testing influenced their outlook on writing in many ways.

**Can being taught highly mechanized rules of writing in k-12 schooling negatively affect a student\'s attitude/motivation towards writing?**

Kathy\'s current relationship with writing varies depending on the kind of writing she\'s doing. She mentions that, \"creative writing like on my own I actually don\'t mind...\[but\] any time when we have like a..big essay assignment\...I do kind of dread it, and I put it off.\" When asked more about why she tends to procrastinate larger, analytical essay assignments, she mentions specific strategies she has to follow, \"I always do my introduction last..I find that writing a thesis before---I will think of something halfway through writing the paper, even if I already have an outline ready\...then I\'ll realize, I wanna explore that instead of whatever..I was planning beforehand. And then I have to redo the whole thing.\" For Kathy, writing isn\'t necessarily difficult for her, but she has these rules for herself that she follows in order to write the most successful paper she can. This would seem to constitute Rose\'s definition of \"blocker\" behavior, as she has specific writing strategies that could prolong the writing process---but that isn\'t necessarily the case. In actuality, Kathy\'s rules help, rather than hinder, as they allow her to achieve higher grades. As she states herself, \"going into high school, late middle school, my relationship with writing was not good because of the grades I had received.\" It took being taught a set of rules/guidelines that helped her understand how to write a paper, and thus, boost her grades, to improve Kathy\'s attitude towards writing. Now, as a college student, Kathy is \"never too worried about the structure \[when writing a paper\].\" What has negatively influenced her motivation to write is the existence of a word count, \"I\'m not somebody that just likes to drone on and on\...I tend to write very concise\[ly\], so those sort of page and word parameters make things very difficult for me.\" This, coupled with her habit of procrastinating, is the main cause of Kathy\'s bouts with writer\'s block---not any sort of rigid rule or strategy.

Natalie has a different approach to writing. In terms of the rules she was taught, she mentions fairly standard rules for essay writing, such as writing an introduction paragraph with a thesis, three body paragraphs, and ending with a conclusion paragraph. Besides that, she doesn\'t mention any specific strategy or rule she has for writing. In regards to MCAS writing specifically, she says, \"obviously, you have to do the intro first, because you have this limited amount of space.\" And as for if these kinds of rules helped or hindered her, Natalie says, \"for me, I think it helped because I need..instructions, and I like specific instructions..but I think you could argue it both ways.\" While some rules may have slowed her down at times, such as the introduction rule she mentions in MCAS writing, she, again, doesn\'t discuss specific routines or approaches she uses, except the three body paragraph rule. Natalie\'s relationship with writing is also unperturbed by any lower grades she receives, or the style of writing she has to complete, \"I\'ve always liked \[writing\] despite grades..even in eleventh grade when my english class was poetry and---I\'m not a huge poet fan, but I like writing and writing poetry even though I don\'t like poetry.\" In other words, for Natalie, different styles or approaches to writing, or even lower grades, don\'t hinder her at all. She enjoys writing and hasn\'t let outside factors influence that. When asked if writing comes easy to her, Natalie responded by saying, \"sometimes I would struggle, depending on what the topic is, but..I would say it comes pretty naturally to me.\" Natalie is very much a \"non-blocker,\" and I argue a major reason for that isn\'t just because she doesn\'t hold onto many rigid rules or routines when approaching writing, but also because grades have never been a barrier for her. Natalie has always had a positive relationship with writing irrespective of how \"harsh\" of a grader a teacher she has is. By and large, rules for writing, and even grades, have little effect on Natalie\'s attitude toward writing. In fact, when asked how she views her relationship with writing, she said frankly, \"I love writing.\"

**To what degree does preparation for standardized testing, in particular, affect a student\'s relationship with writing?**

As mentioned earlier, Kathy attended a private school from sixth through twelfth grade. She took the writing portion of the MCAS once in the fourth grade, but other than that, her preparation for standardized testing revolved around school entrance exams, such as the SAT, and advanced placement classes in high school, such as AP English Language and Composition. Natalie, on the other hand, attended public school from kindergarten to twelfth grade. She took MCAS every year from third grade through tenth grades, and took the writing portion of the exam in fourth, seventh, and tenth grades. Outside of school, she also prepared for school entrance exams. As such, Kathy and Natalie have different experiences when it comes to standardized test preparation, and school in general. Kathy somewhat remembers being taught how to approach MCAS, and mentions how her teachers would say, \"you need to..do it like this, you should do it like \[that\].\" While vague, it gets to the point that Kathy, as mainly a private school student, wasn\'t shaped much by state standardized exam preparation. Conversely, Natalie has far more to say about preparation for MCAS, 

I specifically remember I like to organize out my writing before I like, start for the long comp for example, so I remember---and again, I\'m really bad at topic sentences, so like the topic sentences were always the hardest part for me, but then once like I did like the intro---because obviously, you have to do the intro first, because you have this limited amount of space and stuff, so I would do the intro frist, then the body paragraphs, and then the conclusion. And we were allowed to use quotes, but we really had to like explain---oh, another thing, in the body paragraphs, they would always say, like do your..do your topic sentence, and then your like reasons for whatever you\'re writing about, and then you have to analyze them. Like the most important part was to analyze and then conclude.

While for Natalie, these approaches helped her more than hindered her, I argue it\'s still important to highlight these experiences to better understand how there is a fundamental difference in how Kathy and Natalie were taught to approach writing. Kathy\'s experiences, in middle school in particular, revolve more around approaches or strategies she was taught to specifically help her learn how to write. Whereas, Natalie was taught how to write for MCAS specifically---at least from third grade through tenth grade. Only after tenth grade did the writing curriculum have more freedom, as MCAS isn\'t administered past that grade level. 

With that in mind, I argue that the main differences in Kathy and Natalie\'s attitudes toward writing has to do with their educational histories, as well as how they view, and respond to, grades. I will specifically stress that their outlook on grades is extremely important in how they approach writing, because while they can---and have---been able to learn different and less rigid rules when approaching writing, their respective relationships with grades has continually shaped how they then view their relationships with writing. As mentioned earlier, Kathy was taught a far more relaxed approach to writing, especially in middle school. She mentions how in sixth grade, her teacher had told them, \"he was like write about this and..he didn\'t really tell us how to do it, didn\'t say what we were supposed to be doing.\" For Kathy specifically, this proved to be detrimental because she needs strategies and guidelines in order to understand what makes certain writing effective. As she says, this teacher, \"fed \[her\] to the wolves.\" And so, because she didn\'t understand, yet, how to write, and also wasn\'t scoring high enough for herself, her attitude toward writing was negative. She said, \"if it hadn\'t been for my poor grades in middle school\....then I think that my confidence going into high school would've been much better.\" What did help Kathy build up her \"confidence\" in writing, was being taught the specific functions of a paper, \"my high school teacher\....really mapped out..why we were doing this and why we were writing this and\...how that then conveys to the audience.\" These guidelines helped her achieve higher grades, which, in turn, is what began to positively shape her attitude toward writing. 

Natalie has a far different relationship with grades and writing. As stated earlier, she doesn\'t view a negative grade as indicative of failure. She takes it as a learning opportunity. Writing comes more \"naturally\" to her, so having a teacher who is a rather harsh grader isn\'t necessarily the be-all end-all for Natalie. While Kathy was taught a more relaxed approach to writing in middle school, it was the opposite for Natalie: \"they were more easy-going about \[rules\] in high school.\" Natalie was taught specific approaches to writing from elementary school onwards, as demonstrated earlier how she was able to recall various rules and strategies she was taught during preparation for MCAS in school. These strategies tended to aid her well in writing, but she didn\'t seem to have a specific routine or guideline when it comes to approaching any given writing assignment. In my interview with her, she mentioned basic structural rules, such as the three body paragraph rule, but that is the extent. Ergo, I argue that her own relaxed approach to writing, coupled with her relationship with grades, is what has allowed her to maintain a consistently positive attitude toward writing. Kathy, in comparison, was largely influenced by her grades. When she was taught more comprehensive strategies in high school, she was able to apply them directly to her writing, and thus begin improving her grades. This is the key difference between Kathy and Natalie.

#### **Conclusion:**

When beginning my research, I set out to explore if being taught highly mechanized rules in a student\'s k-12 education could negatively affect their attitude toward writing in college. What I found, instead, is a far more nuanced situation. Therefore, it\'s vital to stress that there are various factors at play here, such as educational history and the type of school a student attended for their k-12 education. Based on my own research, however, I believe that a student\'s own relationship with grades can prove to be more detrimental to their writing process than anything else. As such, a different approach to grading is necessary. Though k-12 teachers don\'t always have much say when it comes to the general curriculum---especially public school teachers---they still hold a tremendous amount of power when it comes to shaping a student\'s attitude and relationship with writing. If, and when, possible, teachers should consider applying a different grading system, such as the labor based grading contract. In the words of Asao B. Inoue, author of Labor-Based Grading Contracts: Building Equity and Inclusion in the Compassionate Writing Classroom, a labor based grading contract is a system \"that calculates final course grades purely by the labor students complete, not by any judgments of the quality of their writing.\" Had Kathy been able to have a teacher in middle school who utilized this system, it could very well mean she wouldn\'t have had such a turbulent relationship with writing. In general, the repercussions of a labor based grading system for students could mean that their individual relationships with writing would at least not include grades as a factor---and for many students, that\'s all they need to begin looking at writing as something to continually improve rather than something they\'re inherently bad at. Because, as Natalie demonstrates, possessing a relaxed attitude about grades can only help a student. 

	
